name: 🏗️ Update CRDs
on:
  workflow_dispatch:
    tag:
      description: 'Execute scenario on specified tag value'
      required: true
      type: string
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  GIT_TAG: ${{ inputs.tag || github.ref_name }}
jobs:
  update-traefik-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: traefik/hub-crds
          path: ${{ github.workspace }}/hub-crds
          ref: ${{ env.GIT_TAG }}
      - name: checkout traefik-helm-chart repo
        uses: actions/checkout@v4
        with:
          repository: traefik/traefik-helm-chart
          ref: master
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ github.workspace }}/traefik-helm-chart
      - name: copy on Traefik main Chart
        run: rsync -crv --delete --exclude='kustomization.yaml' --exclude='gateway-standard-install.yaml' --exclude='traefik.io_*.yaml' --exclude='*.go' ${{ github.workspace }}/hub-crds/pkg/apis/hub/v1alpha1/crd/ ${{ github.workspace }}/traefik-helm-chart/traefik/crds/
      - name: copy on optional CRDs Chart
        run: rsync -crv --delete --exclude='kustomization.yaml' --exclude='gateway-standard-install.yaml' --exclude='traefik.io_*.yaml' --exclude='*.go' ${{ github.workspace }}/hub-crds/pkg/apis/hub/v1alpha1/crd/ ${{ github.workspace }}/traefik-helm-chart/traefik-crds/crds-files/hub/
      - name: create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: traefik-helm-chart
          commit-message: "chore: update CRDs to ${{ env.GIT_TAG }}"
          committer: "Traefiker <traefiker@github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          signoff: false
          branch: update-crds-${{ env.GIT_TAG }}
          delete-branch: true
          title: 'chore: update CRDs to ${{ env.GIT_TAG }}'
          labels: kind/enhancement,status/2-needs-review
          body: |
            This PR was automatically created by ${{ github.workflow }} workflow on run [#${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            This was triggered by commit [${{ github.ref }}](https://github.com/${{ github.repository }}/commits/${{ github.sha }}) on [${{ github.repository }}](https://github.com/${{ github.repository }}).

  update-traefik-hub:
    uses: ./.github/workflows/template-update-crds-go-project.yaml
    with:
      TARGET_REPO: traefik/traefik-hub
      TARGET_BRANCH: main
      CRDS_VERSION: ${{ inputs.tag || github.ref_name }}
    secrets: inherit
  update-hub-api-management:
    uses: ./.github/workflows/template-update-crds-go-project.yaml
    with:
      TARGET_REPO: traefik/hub-api-management
      TARGET_BRANCH: master
      CRDS_VERSION: ${{ inputs.tag || github.ref_name }}
    secrets: inherit
  update-hub-static-analyzer:
    uses: ./.github/workflows/template-update-crds-go-project.yaml
    with:
      TARGET_REPO: traefik/hub-static-analyzer
      TARGET_BRANCH: main
      CRDS_VERSION: ${{ inputs.tag || github.ref_name }}
    secrets: inherit
